### ISSUE TITLE
Overview for missing sending functions

### ISSUE THREAD

**Issue by RAnders00** [robotty/twitch-irc-rs#85]
- [x] whisper
- [x] setColor
- [x] ban - done via #110
- [x] timeout - done via #110
- [x] deleteMessage
- [ ] /me
- [x] say in reply - done via #84 
- [ ] /me in reply (?)
- [x] reply to privmsg with say - done via #84 
- [ ] reply to privmsg with /me (?)

And then utility functions for replying to a PRIVMSG message

#55 #84

**Comment by RAnders00** [comment]
(un)ban and (un)timeout added via #110

**Comment by RAnders00** [comment]
Whisper method added via #164

**Comment by RAnders00** [comment]
Delete method added via #165

**Comment by RAnders00** [comment]
`set_color` added via #167
